<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SelfAssertionTestQuestionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('self_assertion_test_questions')->insert([
            [
                'question'       => json_encode(['ar' => 'لدي القدرة الاجتماعية على الحديث مع الغرباء في المواقف المختلفة ', 'en' => 'I have the social ability to talk to strangers in different situations' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'أحاول سعياً للتعبير عن وجهة نظري ', 'en' => 'I try to express my point of view' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'لا اعرف ما أقوله للأشخاص الذين يعجبونني ', 'en' => 'I don\'t know what to say to people who like you' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ], [
                'question'       => json_encode(['ar' => 'اتقبل النقد والاعتذار عندما يكون مناسباً للموقف  ', 'en' => 'Accept criticism and apologies when appropriate' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],[
                'question'       => json_encode(['ar' => 'اتردد في اجراء مكالمات هاتفية لأي غرض من الأغراض حتى لا احرج الآخرين  ', 'en' => 'I hesitate to make phone calls for any purpose so as not to embarrass others' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'لا تتردد في التعبير عن مشاعري السلبية بطريقة مناسبة اذا وجه لي احدهم إهانة او تحقير', 'en' => 'Feel free to express my negative feelings in an appropriate way if someone insults or insults me' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'اغضب بشكل مبالغ فيه عند حديثي مع الاخرين  ', 'en' => 'I get very angry when I talk to others' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ], [
                'question'       => json_encode(['ar' => 'اتجنب النقاش حول الأسعار مع البائعين حرصاً على مشاعرهم او خوفاً من الاحراج   ', 'en' => 'I avoid discussing prices with sellers out of concern for their feelings or for fear of embarrassment' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'افصح عن هويتي واعرف عن نفسي بجرأة', 'en' => 'I reveal my identity and I know myself boldly' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'عندما اقدم تحية للأخرين اتحدث بصوت خافت جداً', 'en' => 'When I greet others, I speak in a very low voice' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'استطيع انهاء العلاقة مع الافراد الاخرين اذا شعرت انها مؤذية', 'en' => 'I can end the relationship with other people if it feels hurtful' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'اتواصل بصرياً مع الاخرين الذين اتحدث معهم بشكل مناسب', 'en' => 'Make eye contact with others you are speaking appropriately' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
 [
                'question'       => json_encode(['ar' => 'احرص على تجنب إيذاء مشاعر الاخرين حتى عندما اشعر بأنه قد جرح مشاعري', 'en' => 'Be careful to avoid hurting other people\'s feelings even when I feel they have hurt my feelings' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اذا ضايقني قريب او صديق او زميل فإنني افضل ان اخفي مشاعري بدلاً من ان اعبر عن ضيقي منه', 'en' => 'If a relative, friend or colleague annoys me, I prefer to hide my feelings instead of expressing my distress from him.' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'عندما أكون في جديد استطيع التعبير عن احتياجاتي وبالشكل المناسب', 'en' => 'When I\'m new, I can express my needs in an appropriate way' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'اذا كنت في نقاش مع مجموعة من الافراد فإنني لا استطيع التعبير عن وجهة نظري بطريقة لبقة ', 'en' => 'If I\'m in a discussion with a group of people, I can\'t express my point of view in a tactful way' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اذا كنت في موقف تعليمي فإنني اتردد في سؤال المعلم عما لا افهمه ', 'en' => 'If I am in an educational situation, I hesitate to ask the teacher what I do not understand' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اتعامل مع المواقف المحرجة بطريقة عدوانية ', 'en' => 'Deal with embarrassing situations in an aggressive manner' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اذا مدحني شخص ما فإني اشكره بالطريقة المناسبة ', 'en' => 'If someone praises me, I thank them in the appropriate way' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اذا اعجبت بشيء ما او شخص ما فإنني اختار الوقت المناسب للتعبير عن مشاعري ', 'en' => 'If I like something or someone, I choose the right time to express my feelings' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اشعر بالكره والرغبة بالتهجم على الاخرين  ', 'en' => 'I feel hate and want to attack others' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'ليس لدي القدرة في تقديم المديح للآخرين بالشكل المناسب  ', 'en' => 'I do not have the ability to give praise to others properly' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'استطيع تقديم الشكوى للاخرين عندما يسببوا لي الازعاج والايذاء بالشكل المناسب ', 'en' => 'I can complain to others when they cause me annoyance and harm in the appropriate way' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'اذا كان بجانبي اثنان يتحدثان بصوت عالي وأريد الانصات اطلب منهما التزام الهدوء او إتمام محادثتهما في ما بعد ', 'en' => 'If there are two people next to me talking loudly and I want to listen, ask them to stay calm or continue their conversation later' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],



            [
                'question'       => json_encode(['ar' => 'اتردد في دعوة الاخرين لزيارتي وتناول الطعام عندي بسبب خجلي  ', 'en' => 'I hesitate to invite others to visit me and eat with me because of my shyness' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'اجد احراج في إعادة شيء اكتشفت انه غير مناسب ، وكنت قد اشتريته  ', 'en' => 'I am embarrassed to return something which I found to be inappropriate, which I had purchased' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'أكون لطيفاً مع الاخرين ولو على حساب مصلحتي الذاتية   ', 'en' => 'I am kind to others, even at the expense of my own self-interest' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اعبر عن مشاعري بصراحة ووضوح  ', 'en' => 'Express my feelings openly and honestly' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اعرف متى أقول نعم ومتى أقول لا  ', 'en' => 'Know when to say yes and when to say no' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اتردد في المطالبة بحقوقي عندما تكون قليلة جداً وغير مهمة كباقي اجرة مثلاُ   ', 'en' => 'I am kind to others, even at the expense of my own self-interest' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اعطي الاخرين حقوقهم بطريقة لبقة ومؤدبة ولا اعمل على تأجيلها   ', 'en' => 'Give others their rights in a tactful and polite manner and do not delay them' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اذا وجه لي شخص ما انتقاد فإنني اعرف كيف اتعامل معه بشكل مناسب   ', 'en' => 'If someone criticizes me, I know how to deal with them appropriately' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'اجد صعوبة في الحديث امام المسؤولين عن موضوع يخصني وعندها قد يبدو علي تردد وحشرجة الصوت ', 'en' => 'I find it difficult to talk in front of officials about a topic that concerns me, and then I may sound hesitant and rattle of the voice' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],
            [
                'question'       => json_encode(['ar' => 'الجأ الى كبت مشاعري بدلاً من اظهارها حتى لا ازعج الاخرين    ', 'en' => 'I resort to suppressing my feelings rather than expressing them so as not to disturb others' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 1,
                'value_mostly'         => 2,
                'value_sometimes'         => 3,
                'value_scarcely'         => 4,
                'value_never'         => 5,
                'self_assertion_test_id'         => 1,
            ],

            [
                'question'       => json_encode(['ar' => 'لدي ثقة بقدرتي على التعبير عما يجول في خاطري ', 'en' => 'I resort to suppressing my feelings rather than expressing them so as not to disturb others' ], JSON_UNESCAPED_UNICODE) ,
                'always'         => json_encode(['ar' => 'دائماً' , 'en' => 'always' ], JSON_UNESCAPED_UNICODE) ,
                'mostly'         => json_encode(['ar' => 'غالبا' , 'en' => 'mostly' ], JSON_UNESCAPED_UNICODE) ,
                'sometimes'         => json_encode(['ar' => 'احيانا' , 'en' => 'sometimes' ], JSON_UNESCAPED_UNICODE) ,
                'scarcely'         => json_encode(['ar' => 'نادرا' , 'en' => 'scarcely' ], JSON_UNESCAPED_UNICODE) ,
                'never'         => json_encode(['ar' => 'ابدا' , 'en' => 'never' ], JSON_UNESCAPED_UNICODE) ,
                'value_always'         => 5,
                'value_mostly'         => 4,
                'value_sometimes'         => 3,
                'value_scarcely'         => 2,
                'value_never'         => 1,
                'self_assertion_test_id'         => 1,
            ],

        ]);
    }
}
