<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaylorForAnxietyTestQuestionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('taylor_for_anxiety_test_questions')->insert([
            [
                'question' => json_encode(['ar' => 'نومي مضطرب ومتقطع ', 'en' => 'The sleep is restless and interrupted'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],

            [
                'question' => json_encode(['ar' => 'مرت بي أوقات لا أستطيع خلالها النوم بسبب القلق ', 'en' => 'I can\'t sleep for a long time because of anxiety'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],

            [
                'question' => json_encode(['ar' => 'مخاوفي قليله جدا مقارنه باصدقائي  ', 'en' => 'Fear is little compared to friendship'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],

            [
                'question' => json_encode(['ar' => 'اعتقد أنني أكثر عصبية من معظم الناس ', 'en' => 'I think I am more nervous than most people'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ], [
                'question' => json_encode(['ar' => 'تنتابني احلام مزعجه (كوابيس) كل عده ليالي', 'en' => 'I have bad dreams (nightmares) every few nights'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ], [
                'question' => json_encode(['ar' => ' لدي متاعب أحيانا في معدتي', 'en' => 'I sometimes have trouble with my stomach'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => '  غالبا ما أالحظ أن يداي ترتجفان عندما أحاول القيام بعمل ما', 'en' => 'I often notice that my hands tremble when I try to do something'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أعاني أحيانا من نوبات إسهال', 'en' => 'I sometimes have bouts of diarrhea'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ], [
                'question' => json_encode(['ar' => 'تثير قلقي أمور العمل والعمال', 'en' => 'I worry about work and workers'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'تصيبني نوبات من الغثيان (غمامات النفس)', 'en' => 'I get bouts of nausea (darkness of breath)'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'كثيراً ما أخشى أن يحمر وجهي خجلا', 'en' => 'I often fear that my face will turn red'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ], [
                'question' => json_encode(['ar' => 'أشعر بجوع في كل الاوقات تقريبا', 'en' => 'I feel hungry almost all the time'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أثق في نفسي كثيرا', 'en' => 'I trust myself a lot'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أتعب بسرعة', 'en' => 'I get tired quickly'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => ' يجعلني الانتظار عصبيا', 'en' => 'It makes me nervous waiting'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أشعر بالاثاره لدرجة أن النوم يتعذر علي', 'en' => 'I get so excited that I can\'t sleep'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'عادًة ما أكون هادئا', 'en' => 'I\'m usually calm'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => ' تمر بي فترات من عدم الاستقرار  لدرجة أنني ال أستطيع الجلوس طويلا في مقعدي', 'en' => 'You go through periods of so much instability that I can\'t sit very long in my seat'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'لا أشعر بالسعادة معظم الوقت', 'en' => 'I don\'t feel happy most of the time'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'من السهل أن أركز ذهني في عمل ما', 'en' => 'It\'s easy to focus my mind on something'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أشعر بجوع في كل األوقات تقريبا', 'en' => 'I feel hungry almost all the time'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'اشعر بالقلق على شئ ما، أو شخص ما، طوال الوقت تقريبا', 'en' => 'I worry about something, or someone, almost all the time'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'لا أتهيب الأزمات والشدائد', 'en' => 'I am not afraid of crises and adversity'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أود أن أصبح سعيداً كما يبدو للآخرين', 'en' => 'I want to be as happy as it seems to others'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],

            [
                'question' => json_encode(['ar' => 'كثيراً ما أجد نفسي قلقاً على شيء ما', 'en' => 'I often find myself worrying about something'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أشعر أحياناً بشكل مؤكد أنه لا فائدة لي', 'en' => 'Sometimes I feel for sure that it is of no use to me'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'اشعر احيانا انني اتمزق ', 'en' => 'Sometimes I feel like I\'m torn'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'أعرق بسهولة حتى في الأيام الباردة', 'en' => 'I sweat easily even on cold days'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => ' الحياة صعبة بالنسبة لي في أغلب األوقات', 'en' => 'Life is hard for me most of the time'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => 'ال يقلقني ما يحتمل أن أقابله من سوء حظ', 'en' => 'I don\'t worry about the misfortune that I might encounter'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],
            [
                'question' => json_encode(['ar' => ' إنني حساس بدرجة غير عادية ', 'en' => 'I am extraordinarily sensitive'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' لاحظت ان قلبي يخفق بشده واحيانا تتيهيج نفسي  ', 'en' => 'I noticed that my heart was pounding so hard and sometimes I got agitated'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' لا ابكي بسهوله ', 'en' => 'I don\'t cry easily'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' خشيت أشياء أو أشخاص أعرف أنهم ال يستطيعون إيذائي ', 'en' => 'I was afraid of things or people that I knew couldn\'t hurt me'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' لدي قابلية التأثر بالأحداث تأثراً شديداً ', 'en' => 'I have a strong vulnerability to events'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' كثيراً ما أصاب بصداع ', 'en' => 'I often get headaches'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' لابد أن أعترف أنني شعرت بالقلق على أشياء لا قيمة لها ', 'en' => 'I have to admit that I worried about things of no value'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' لا أستطيع أن أركز تفكيري في شيء واحد ', 'en' => 'I can\'t focus my mind on one thing'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' لاأرتبك بسهولة ', 'en' => 'I don\'t get confused easily'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' اعتقد احيانا انني لا اصلح بالمره  ', 'en' => 'Sometimes I think I don\'t fit at all'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' انا شخص متوتر جدا ', 'en' => 'I am a very nervous person'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' ارتبك احيانا بدرجه تجعل العرق يتساقط مني بصوره تضايقني جدا  ', 'en' => 'Sometimes I get confused to the point that sweat drips from me in a way that annoys me very much'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' يحمر وجهي بدرجه اكبر عندما اتحدث مع الاخرين  ', 'en' => 'My face turns red when I talk to others'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],  [
                'question' => json_encode(['ar' => ' أنا أكثر حساسية من غالبية الناس ', 'en' => 'I\'m more sensitive than most people'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => 'مرت بي أوقات شعرت خاللها بتراكم الصعاب بحيث ال أستطيع التغلب
عليها', 'en' => 'There were times when I felt so many difficulties that I could not overcome
on her'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => ' اكون متوتر للغايه اثناء القيام بعمل ما  ', 'en' => 'I get very nervous while doing something'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => ' يداي وقدماي باردتان في العادة ', 'en' => 'My hands and feet are usually cold'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => ' أحيانا أحلم بأشياء أفضل الاحتفاظ بها لنفسك ', 'en' => 'Sometimes I dream of better things to keep to yourself'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => ' لا تنقصني الثقة بالنفس ', 'en' => 'I\'m more sensitive than most people'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => ' أصاب أحيانا بالإمساك ', 'en' => 'I get constipated sometimes'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 1,
                'value_no' => 0,
                'taylor_id' => 1,
            ],[
                'question' => json_encode(['ar' => ' لا يحمر وجهي أبداً من الخجل ', 'en' => 'My face never turns red from shame'], JSON_UNESCAPED_UNICODE),
                'yes' => json_encode(['ar' => 'نعم', 'en' => 'yes'], JSON_UNESCAPED_UNICODE),
                'no' => json_encode(['ar' => 'لا', 'en' => 'no'], JSON_UNESCAPED_UNICODE),
                'value_yes' => 0,
                'value_no' => 1,
                'taylor_id' => 1,
            ],

        ]);
    }
}
